/**
 * MSDF atlas parsing (ARCHITECTURE §23.3), including the font this repository
 * ships for the text example (examples/text/font/cozy.json, regenerated by
 * examples/text/tools/gen-font.mjs).
 */
import { Texture } from '../scene/Texture';
import type { TextureHandle } from '../scene/types';
import { SpriteInstanceFlag } from '../types/layouts';
import { createGlyphSource, msdfPageUrl, parseMsdfFont } from './msdf';

function page(width: number, height: number): TextureHandle {
  return Texture.fromPixels(width, height, new Uint8Array(width * height * 4));
}

// Node built-ins without @types/node (tsconfig types: webgpu + jest only).
declare const require: (id: string) => {
  readFileSync(path: string, encoding: 'utf8'): string;
};
declare const __dirname: string;

const COZY = JSON.parse(
  require('fs').readFileSync(
    `${__dirname}/../../examples/text/font/cozy.json`,
    'utf8',
  ),
) as Record<string, unknown>;

describe('parseMsdfFont', () => {
  it('scales em-relative metrics to the atlas size', () => {
    const font = parseMsdfFont(
      {
        atlas: {
          size: 32,
          distanceRange: 4,
          width: 64,
          height: 64,
          yOrigin: 'top',
        },
        metrics: {
          emSize: 1,
          lineHeight: 1.25,
          ascender: 0.75,
          descender: -0.25,
        },
        glyphs: [],
      },
      page(64, 64),
    );
    expect(font.size).toBe(32);
    expect(font.lineHeight).toBe(40);
    expect(font.ascender).toBe(24);
    expect(font.descender).toBe(-8);
    expect(font.distanceRange).toBe(4);
  });

  it('turns planeBounds into a y-down quad and atlasBounds into a frame', () => {
    const font = parseMsdfFont(
      {
        atlas: { size: 10, width: 100, height: 100, yOrigin: 'top' },
        metrics: { emSize: 1 },
        glyphs: [
          {
            unicode: 65,
            advance: 0.6,
            planeBounds: { left: -0.1, bottom: -0.2, right: 0.7, top: 0.8 },
            atlasBounds: { left: 10, top: 20, right: 18, bottom: 30 },
          },
        ],
      },
      page(100, 100),
    );
    const a = font.glyph(65);
    expect(a?.advance).toBe(6);
    expect(a?.offsetX).toBeCloseTo(-1);
    expect(a?.offsetY).toBeCloseTo(-8);
    expect(a?.width).toBeCloseTo(8);
    expect(a?.height).toBeCloseTo(10);
    expect(a?.texture?.frame).toEqual({ x: 10, y: 20, width: 8, height: 10 });
  });

  it('flips atlasBounds when yOrigin is the page bottom', () => {
    const font = parseMsdfFont(
      {
        atlas: { size: 10, width: 100, height: 100, yOrigin: 'bottom' },
        metrics: { emSize: 1 },
        glyphs: [
          {
            unicode: 66,
            advance: 0.6,
            planeBounds: { left: 0, bottom: 0, right: 0.8, top: 1 },
            atlasBounds: { left: 10, bottom: 70, right: 18, top: 80 },
          },
        ],
      },
      page(100, 100),
    );
    // top 80 counted from the bottom is y = 100 - 80 = 20 from the top.
    expect(font.glyph(66)?.texture?.frame).toEqual({
      x: 10,
      y: 20,
      width: 8,
      height: 10,
    });
  });

  it('records whitespace as an advance with no quad', () => {
    const font = parseMsdfFont(
      {
        atlas: { size: 10, width: 8, height: 8 },
        metrics: { emSize: 1 },
        glyphs: [{ unicode: 32, advance: 0.5 }],
      },
      page(8, 8),
    );
    expect(font.glyph(32)?.advance).toBe(5);
    expect(font.glyph(32)?.texture).toBeNull();
  });

  it('reads kerning pairs, and answers 0 for unknown ones', () => {
    const font = parseMsdfFont(
      {
        atlas: { size: 10, width: 8, height: 8 },
        metrics: { emSize: 1 },
        glyphs: [],
        kerning: [{ unicode1: 65, unicode2: 86, advance: -0.05 }],
      },
      page(8, 8),
    );
    expect(font.kerning(65, 86)).toBeCloseTo(-0.5);
    expect(font.kerning(86, 65)).toBe(0);
  });

  it('rejects malformed atlases', () => {
    expect(() => parseMsdfFont(null, page(8, 8))).toThrow(/not an object/);
    expect(() => parseMsdfFont({}, page(8, 8))).toThrow(/atlas/);
    expect(() =>
      parseMsdfFont({ atlas: { size: 0 }, glyphs: [] }, page(8, 8)),
    ).toThrow(/size/);
    expect(() => parseMsdfFont({ atlas: { size: 16 } }, page(8, 8))).toThrow(
      /glyphs/,
    );
  });

  it('names the page image from the JSON', () => {
    expect(msdfPageUrl(COZY)).toBe('cozy.png');
    expect(msdfPageUrl({})).toBeNull();
    expect(msdfPageUrl({ atlas: { image: 'a.png' } })).toBe('a.png');
  });
});

describe('the bundled cozy font', () => {
  const atlas = COZY.atlas as Record<string, number>;
  const font = parseMsdfFont(COZY, page(atlas.width, atlas.height));

  it('covers printable ASCII plus the ellipsis', () => {
    for (let code = 32; code <= 126; code++) {
      expect(font.glyph(code)).toBeDefined();
    }
    expect(font.glyph(0x2026)).toBeDefined();
    expect(font.glyph(0x4e2d)).toBeUndefined();
  });

  it('is monospaced and sits inside its page', () => {
    const advance = font.glyph(65)?.advance;
    for (let code = 33; code <= 126; code++) {
      const glyph = font.glyph(code);
      expect(glyph?.advance).toBe(advance);
      const frame = glyph?.texture?.frame;
      expect(frame).toBeDefined();
      expect((frame?.x ?? 0) + (frame?.width ?? 0)).toBeLessThanOrEqual(
        atlas.width,
      );
      expect((frame?.y ?? 0) + (frame?.height ?? 0)).toBeLessThanOrEqual(
        atlas.height,
      );
    }
  });

  it('has a space with an advance and no quad', () => {
    expect(font.glyph(32)?.texture).toBeNull();
    expect(font.glyph(32)?.advance).toBeGreaterThan(0);
  });
});

describe('createGlyphSource', () => {
  const font = parseMsdfFont(
    { atlas: { size: 10, width: 8, height: 8 }, metrics: {}, glyphs: [] },
    page(8, 8),
  );

  it('flags its glyphs as MSDF and never waits', () => {
    const source = createGlyphSource({ font });
    expect(source.instanceFlags).toBe(SpriteInstanceFlag.MSDF);
    expect(source.ensure('abc')).toBeNull();
    expect(source.font).toBe(font);
  });

  it('is shared per font asset', () => {
    expect(createGlyphSource({ font })).toBe(
      createGlyphSource({ font, size: 20 }),
    );
  });

  it('refuses a system font descriptor', () => {
    expect(() => createGlyphSource({ font: { family: 'Menlo' } })).toThrow(
      /Canvas2D/,
    );
  });
});
