// GPU.Text (ARCHITECTURE §23): MSDF text through the asset loader, wrapping
// and alignment, a per-frame counter that rewrites one glyph instance, and
// the Canvas2D fallback for an installed system font.
//
//   ?backend=webgl2  force a backend ('auto' by default, 'webgpu' also valid)
//   ?worker=1        run the core in a worker (layout stays on the front)
//   ?system=Menlo    family for the Canvas2D sample (default 'monospace')
//   ?size=28         size of the headline, px
//
// The MSDF font in font/ is generated by `node examples/text/tools/gen-font.mjs`.
import * as GPU from 'cozygpu';

const params = new URLSearchParams(location.search);
const backendParam = params.get('backend');
const backend: 'auto' | 'webgpu' | 'webgl2' =
  backendParam === 'webgpu' || backendParam === 'webgl2'
    ? backendParam
    : 'auto';
const WORKER = params.get('worker') === '1';
const SYSTEM_FAMILY = params.get('system') ?? 'monospace';
const HEADLINE_SIZE = Math.max(8, Number(params.get('size') ?? 34));

const PARAGRAPH =
  'Text is a Container of glyph sprites, so every glyph is an ordinary ' +
  'sprite instance and batches with the sprites around it. Layout runs on ' +
  'the front in both renderer modes and touches no DOM.';

async function main(): Promise<void> {
  const canvas = document.getElementById('view') as HTMLCanvasElement;
  const hud = document.getElementById('hud') as HTMLElement;

  const renderer = await GPU.createRenderer({
    canvas,
    background: 0x101420,
    backend,
    worker: WORKER ? { url: '/build/examples/cozygpu.worker.js' } : false,
    assets: { baseUrl: new URL('./font/', location.href).href },
  });
  // Dev handle for the headless verification driver (examples only).
  (globalThis as { __renderer?: unknown }).__renderer = renderer;

  const handle = await renderer.assets.load<GPU.FontAsset>({
    url: 'cozy.json',
    kind: 'font',
  });
  const font = handle.value;
  const world = new GPU.Container();
  renderer.stage.addChild(world);
  const ticker = GPU.ticker(renderer);

  // ── Headline ──────────────────────────────────────────────────────────────
  const headline = new GPU.Text('cozygpu text', {
    font,
    size: HEADLINE_SIZE,
    fill: 0xffd479,
  });
  headline.setPosition(32, 28);
  world.addChild(headline);

  // ── Wrapped paragraph, one node per alignment ─────────────────────────────
  const WRAP = 380;
  const aligns: GPU.TextStyle['align'][] = [
    'left',
    'center',
    'right',
    'justify',
  ];
  const columns: GPU.Text[] = [];
  for (let i = 0; i < aligns.length; i++) {
    const column = new GPU.Text(PARAGRAPH, {
      font,
      size: 15,
      fill: 0xc8d4f0,
      maxWidth: WRAP,
      wrap: 'word',
      align: aligns[i],
      lineHeight: 1.05,
    });
    column.setPosition(32 + (i % 2) * (WRAP + 40), 96 + ((i / 2) | 0) * 170);
    world.addChild(column);
    columns.push(column);
  }

  // ── Ellipsis and maxLines ─────────────────────────────────────────────────
  const clipped = new GPU.Text(PARAGRAPH, {
    font,
    size: 15,
    fill: 0x8fe3a0,
    maxWidth: WRAP,
    maxLines: 2,
    ellipsis: true,
  });
  clipped.setPosition(32, 440);
  world.addChild(clipped);

  // ── Counter: only the digits that change rewrite an instance ──────────────
  const counter = new GPU.Text('frame 0', { font, size: 20, fill: 0x9fd7ff });
  counter.setPosition(32, 490);
  world.addChild(counter);

  // ── Canvas2D fallback: any installed font, and emoji ───────────────────────
  const system = new GPU.Text(`system font: ${SYSTEM_FAMILY} 0123 \u{1f389}`, {
    font: { family: SYSTEM_FAMILY, atlasSize: 64 },
    size: 20,
    fill: 0xffffff,
  });
  system.setPosition(32, 530);
  world.addChild(system);
  await Promise.all([headline.ready, system.ready, clipped.ready]);

  // ── Frame loop ────────────────────────────────────────────────────────────
  let frames = 0;
  let hudTime = 0;
  let spin = 0;
  ticker.add(dt => {
    frames++;
    counter.text = `frame ${frames}`;
    // Glyphs are ordinary children, so the whole node transforms for free.
    spin += dt;
    headline.rotation = Math.sin(spin) * 0.02;
    hudTime += dt;
    if (hudTime < 0.25) return;
    hudTime = 0;
    hud.textContent =
      `backend ${renderer.info.backend}  worker ${renderer.info.worker}  ` +
      `fps ${ticker.fps.toFixed(0)}  draw calls ${renderer.stats.drawCalls}\n` +
      `glyphs ${columns[0].metrics.glyphs} per column, ` +
      `${columns[0].metrics.lines} lines, ` +
      `paragraph ${columns[0].metrics.width.toFixed(0)}x` +
      `${columns[0].metrics.height.toFixed(0)} px`;
  });

  // Machine-readable summary for headless checks.
  setTimeout(() => {
    console.log(
      'TEXT_SUMMARY ' +
        JSON.stringify({
          backend: renderer.info.backend,
          worker: renderer.info.worker,
          headlineGlyphs: headline.metrics.glyphs,
          paragraphLines: columns[0].metrics.lines,
          clippedLines: clipped.metrics.lines,
          systemGlyphs: system.metrics.glyphs,
          counterGlyphs: counter.metrics.glyphs,
          drawCalls: renderer.stats.drawCalls,
        }),
    );
  }, 2000);

  window.addEventListener('pagehide', () => {
    ticker.destroy();
    renderer.destroy();
  });
}

main().catch(error => {
  console.error(error);
  const hud = document.getElementById('hud');
  if (hud) hud.textContent = String(error);
});
